services:
  - type: web
    name: landing-zemelni
    runtime: python
    buildCommand: ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: RENDER
        value: "true"
