# Generated by Django 6.0.2 on 2026-02-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Про компанію', max_length=120, verbose_name='Заголовок секції')),
                ('philosophy_title', models.CharField(default='Наша філософія: Справедлива ціна народжується в конкуренції', max_length=160, verbose_name='Заголовок філософії')),
                ('philosophy_text', models.TextField(verbose_name='Текст філософії')),
            ],
            options={
                'verbose_name': 'Секція «Про компанію»',
                'verbose_name_plural': 'Секція «Про компанію»',
            },
        ),
        migrations.CreateModel(
            name='AdvantageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_key', models.CharField(choices=[('shield', 'Щит (безпека)'), ('chart', 'Графік (вигода)'), ('clock', 'Годинник (досвід)'), ('key', 'Ключ (під ключ)'), ('eye', 'Око (моніторинг)'), ('checkmark', 'Галочка (гарантія)'), ('star', 'Зірка'), ('map', 'Карта')], default='shield', max_length=20, verbose_name='Іконка')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Опис')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Перевага',
                'verbose_name_plural': 'Переваги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AdvantagesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Чому обирають «Центр Земельних Аукціонів»?', max_length=120, verbose_name='Заголовок секції')),
                ('subtitle', models.CharField(default='Ми знаємо ціну кожного гектара та кожної хвилини вашого часу.', max_length=200, verbose_name='Підзаголовок')),
                ('footer_quote', models.TextField(default='Ми працюємо на ваш результат, бо розуміємо: успішний аукціон — це початок вашого прибутку.', verbose_name='Цитата внизу блоку')),
            ],
            options={
                'verbose_name': 'Секція «Переваги»',
                'verbose_name_plural': 'Секція «Переваги»',
            },
        ),
        migrations.CreateModel(
            name='AuctionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Що таке аукціон?', max_length=120, verbose_name='Заголовок секції')),
                ('platform_title', models.CharField(default='Що таке Prozorro.Продажі?', max_length=120, verbose_name='Заголовок платформи')),
                ('platform_text', models.TextField(verbose_name='Опис платформи')),
                ('seller_title', models.CharField(default='Для власника (Продавця)', max_length=80, verbose_name='Заголовок блоку продавця')),
                ('seller_text', models.TextField(verbose_name='Текст для продавця')),
                ('buyer_title', models.CharField(default='Для фермера (Покупця)', max_length=80, verbose_name='Заголовок блоку покупця')),
                ('buyer_text', models.TextField(verbose_name='Текст для покупця')),
                ('important_note', models.TextField(verbose_name='Важлива примітка (виноска)')),
            ],
            options={
                'verbose_name': 'Секція «Що таке аукціон»',
                'verbose_name_plural': 'Секція «Що таке аукціон»',
            },
        ),
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Почніть свій шлях до успішної угоди вже сьогодні', max_length=120, verbose_name='Заголовок')),
                ('description', models.TextField(default="Ми завжди на зв'язку, щоб обговорити вашу майбутню ділянку.", verbose_name='Опис')),
                ('form_title', models.CharField(default='Залишити заявку на безкоштовний аналіз', max_length=120, verbose_name='Заголовок форми')),
                ('form_btn_text', models.CharField(default='ОТРИМАТИ КОНСУЛЬТАЦІЮ ЕКСПЕРТА', max_length=80, verbose_name='Текст кнопки форми')),
                ('privacy_note', models.CharField(default='Ваші дані в безпеці. Ми гарантуємо повну конфіденційність кожного звернення.', max_length=200, verbose_name='Приміт. конфіденційності')),
            ],
            options={
                'verbose_name': 'Секція «Контакти»',
                'verbose_name_plural': 'Секція «Контакти»',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ЦЕНТР ЗЕМЕЛЬНИХ АУКЦІОНІВ', max_length=120, verbose_name='Заголовок')),
                ('subtitle', models.TextField(default='Професійний супровід купівлі та продажу землі через аукціон Prozorro.Продажі.', verbose_name='Підзаголовок')),
                ('btn_buy_text', models.CharField(default='ХОЧУ КУПИТИ ЗЕМЛЮ', max_length=60, verbose_name='Кнопка «Купити»')),
                ('btn_sell_text', models.CharField(default='ХОЧУ ПРОДАТИ ЗЕМЛЮ', max_length=60, verbose_name='Кнопка «Продати»')),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Фонове зображення')),
                ('overlay_opacity', models.FloatField(default=0.65, verbose_name='Прозорість фільтра (0–1)')),
            ],
            options={
                'verbose_name': 'Hero-секція',
                'verbose_name_plural': 'Hero-секція',
            },
        ),
        migrations.CreateModel(
            name='LeadSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('interest', models.CharField(choices=[('buy', 'Купити землю'), ('sell', 'Продати землю'), ('estimate', 'Оцінка ділянки')], max_length=10, verbose_name='Запит')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Оброблено')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('buyer', 'Для покупців'), ('seller', 'Для продавців')], max_length=10, verbose_name='Категорія')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Опис')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Наші послуги',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Наші Послуги', max_length=120, verbose_name='Заголовок секції')),
                ('steps_title', models.CharField(default='Як ми працюємо: 5 кроків до успішної угоди', max_length=160, verbose_name='Заголовок блоку кроків')),
            ],
            options={
                'verbose_name': 'Секція «Послуги»',
                'verbose_name_plural': 'Секція «Послуги»',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Логотип')),
                ('phone', models.CharField(default='+380 00 000 00 00', max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(default='info@example.com', max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адреса офісу')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('viber_url', models.URLField(blank=True, verbose_name='Viber')),
                ('whatsapp_url', models.URLField(blank=True, verbose_name='WhatsApp')),
                ('call_btn_text', models.CharField(default='Замовити дзвінок', max_length=60, verbose_name='Текст кнопки дзвінка')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
        migrations.CreateModel(
            name='StatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=40, verbose_name='Значення')),
                ('label', models.CharField(max_length=120, verbose_name='Підпис')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика (цифри)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер кроку')),
                ('title', models.CharField(max_length=160, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Опис')),
                ('is_highlighted', models.BooleanField(default=False, verbose_name='Виділити золотим (Крок 4)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Крок роботи',
                'verbose_name_plural': 'Як ми працюємо (кроки)',
                'ordering': ['order'],
            },
        ),
    ]
