# Generated by Django 6.0.1 on 2026-03-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_update_site_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='philosophy_title',
            field=models.CharField(default='Надійність, якість та індивідуальний підхід', max_length=160, verbose_name='Заголовок філософії'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title',
            field=models.CharField(default='Про підприємство', max_length=120, verbose_name='Заголовок секції'),
        ),
        migrations.AlterField(
            model_name='advantagessection',
            name='footer_quote',
            field=models.TextField(default='Ціни від виробника та повний спектр послуг — від проектування до монтажу по всій Україні.', verbose_name='Цитата внизу блоку'),
        ),
        migrations.AlterField(
            model_name='advantagessection',
            name='subtitle',
            field=models.CharField(default='Ми гарантуємо надійність нашого обладнання та високу якість виконання робіт.', max_length=200, verbose_name='Підзаголовок'),
        ),
        migrations.AlterField(
            model_name='advantagessection',
            name='title',
            field=models.CharField(default='Чому обирають ПП «Укркотлобуд»?', max_length=120, verbose_name='Заголовок секції'),
        ),
        migrations.AlterField(
            model_name='auctionsection',
            name='buyer_title',
            field=models.CharField(default='Для громад та агросектору', max_length=80, verbose_name='Заголовок блоку покупця'),
        ),
        migrations.AlterField(
            model_name='auctionsection',
            name='platform_title',
            field=models.CharField(default='Сертифіковане виробництво', max_length=120, verbose_name='Заголовок платформи'),
        ),
        migrations.AlterField(
            model_name='auctionsection',
            name='seller_title',
            field=models.CharField(default="Для промислових об'єктів", max_length=80, verbose_name='Заголовок блоку продавця'),
        ),
        migrations.AlterField(
            model_name='auctionsection',
            name='title',
            field=models.CharField(default='Наші можливості', max_length=120, verbose_name='Заголовок секції'),
        ),
        migrations.AlterField(
            model_name='contactsection',
            name='description',
            field=models.TextField(default='Наші фахівці допоможуть підібрати обладнання, розрахувати вартість та нададуть професійну консультацію.', verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='contactsection',
            name='form_btn_text',
            field=models.CharField(default='ОТРИМАТИ ПРОПОЗИЦІЮ', max_length=80, verbose_name='Текст кнопки форми'),
        ),
        migrations.AlterField(
            model_name='contactsection',
            name='form_title',
            field=models.CharField(default='Залишити заявку на розрахунок', max_length=120, verbose_name='Заголовок форми'),
        ),
        migrations.AlterField(
            model_name='contactsection',
            name='privacy_note',
            field=models.CharField(default='Ми гарантуємо конфіденційність вашого звернення та оперативну відповідь.', max_length=200, verbose_name='Приміт. конфіденційності'),
        ),
        migrations.AlterField(
            model_name='contactsection',
            name='title',
            field=models.CharField(default="Маєте запитання? Зв'яжіться з нами!", max_length=120, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='btn_buy_text',
            field=models.CharField(default='КАТАЛОГ ПРОДУКЦІЇ', max_length=60, verbose_name='Кнопка «Купити»'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='btn_sell_text',
            field=models.CharField(default='ОТРИМАТИ КОНСУЛЬТАЦІЮ', max_length=60, verbose_name='Кнопка «Продати»'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='subtitle',
            field=models.TextField(default='Виробництво промислових котлів, водонапірних башт Рожновського та металоконструкцій будь-якої складності. Якість, перевірена часом.', verbose_name='Підзаголовок'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title',
            field=models.CharField(default='ПП «УКРКОТЛОБУД» — ВАШ НАДІЙНИЙ ПАРТНЕР У СФЕРІ ОПАЛЕННЯ', max_length=120, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='leadsubmission',
            name='interest',
            field=models.CharField(choices=[('buy', 'Водонапірні башти'), ('sell', 'Котли та опалення'), ('estimate', 'Металоконструкції')], max_length=10, verbose_name='Запит'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='category',
            field=models.CharField(choices=[('buyer', 'Основна продукція'), ('seller', 'Додаткові послуги')], max_length=10, verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='servicessection',
            name='steps_title',
            field=models.CharField(default='Як ми працюємо: від замовлення до запуску', max_length=160, verbose_name='Заголовок блоку кроків'),
        ),
        migrations.AlterField(
            model_name='servicessection',
            name='title',
            field=models.CharField(default='Наша продукція', max_length=120, verbose_name='Заголовок секції'),
        ),
    ]
