# Generated by Django 6.0.1 on 2026-03-06 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_alter_aboutsection_philosophy_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuctionSection',
            new_name='ProductionSection',
        ),
        migrations.AlterModelOptions(
            name='productionsection',
            options={'verbose_name': 'Секція «Наші можливості»', 'verbose_name_plural': 'Секція «Наші можливості»'},
        ),
    ]
