# Generated by Django 6.0.1 on 2026-03-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_rename_auctionsection_productionsection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='philosophy_title',
            field=models.CharField(default='Надійний виробник башт Рожновського з 20-річним досвідом', max_length=160, verbose_name='Заголовок філософії'),
        ),
        migrations.AlterField(
            model_name='advantagessection',
            name='footer_quote',
            field=models.TextField(default="Від розрахунку до здачі об'єкту — ми беремо на себе все. Доставка та монтаж башт Рожновського у будь-який куточок України.", verbose_name='Цитата внизу блоку'),
        ),
        migrations.AlterField(
            model_name='advantagessection',
            name='subtitle',
            field=models.CharField(default='Власне виробництво, монтаж під ключ та ціни без посередників по всій Україні.', max_length=200, verbose_name='Підзаголовок'),
        ),
        migrations.AlterField(
            model_name='advantagessection',
            name='title',
            field=models.CharField(default='Чому обирають наші башти Рожновського?', max_length=120, verbose_name='Заголовок секції'),
        ),
        migrations.AlterField(
            model_name='contactsection',
            name='description',
            field=models.TextField(default="Наші фахівці розрахують вартість башти, підберуть оптимальний об'єм та нададуть консультацію щодо монтажу.", verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='contactsection',
            name='title',
            field=models.CharField(default='Замовити башту Рожновського', max_length=120, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='btn_buy_text',
            field=models.CharField(default='ЗАМОВИТИ БАШТУ', max_length=60, verbose_name='Кнопка «Купити»'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='subtitle',
            field=models.TextField(default='Виготовляємо сталеві водонапірні башти 15, 25, 50 м³. Монтаж під ключ, доставка по всій Україні. Гарантія та сертифікати.', verbose_name='Підзаголовок'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title',
            field=models.CharField(default='ВОДОНАПІРНІ БАШТИ РОЖНОВСЬКОГО — ВІД ВИРОБНИКА', max_length=120, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='servicessection',
            name='title',
            field=models.CharField(default='Наша продукція та послуги', max_length=120, verbose_name='Заголовок секції'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='call_btn_text',
            field=models.CharField(default='Замовити башту', max_length=60, verbose_name='Текст кнопки дзвінка'),
        ),
    ]
