# Generated by Django 6.0.1 on 2026-03-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_update_tower_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='phone2',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Телефон 2'),
        ),
    ]
