# Generated by Django 5.2.11 on 2026-03-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_add_phone2_to_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='subtitle',
            field=models.TextField(default='Виготовляємо сталеві водонапірні башти від 10 до 200 м³. Монтаж під ключ, доставка по всій Україні. Гарантія та сертифікати.', verbose_name='Підзаголовок'),
        ),
    ]
